language: python
sudo: enabled
dist: bionic

python:
    - "3.8"
env:
    global:
     - TRAVIS=true

before_install:
   - sudo apt update

install:
    - pip install -r requirements.txt

script:
    python main.py
